# Generated by Django 4.2.22 on 2025-07-03 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppHome', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='author',
            field=models.CharField(max_length=100, verbose_name='Имя автора'),
        ),
    ]
