# Generated by Django 4.2.22 on 2025-07-03 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppService', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consultationrequest',
            options={'ordering': ['-submitted_at'], 'verbose_name': 'Заявку', 'verbose_name_plural': 'Заявки на консультацию'},
        ),
    ]
